//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackathonProje.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hackhathonP01Entities3 : DbContext
    {
        public hackhathonP01Entities3()
            : base("name=hackhathonP01Entities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblIsletme> tblIsletme { get; set; }
        public virtual DbSet<tblIsletmeKullanici> tblIsletmeKullanici { get; set; }
        public virtual DbSet<tblKullanici> tblKullanici { get; set; }
        public virtual DbSet<tblKuponlar> tblKuponlar { get; set; }
        public virtual DbSet<tblKuponlarim> tblKuponlarim { get; set; }
        public virtual DbSet<tblPuanDetay> tblPuanDetay { get; set; }
    }
}
